### ISSUE TITLE
Fetching multiple pages

### ISSUE THREAD

**Issue by Pokac** [BookingSync/rest-request-php#7]
Would it be possible to have an example to fetch all bookings pages?

**Comment by JulienItard** [comment]
@Pokac 

Hello Pokac. 

If I understand it right, you want to fetch all booking pages to get like one variable with all bookings inside ?

**Comment by ZenCocoon** [comment]
@Pokac This example should put you on the good track https://github.com/BookingSync/rest-request-php/pull/10

Enjoy!
